# docker-compose.yml

version: '3.5'

services:
    database:
        command: ['--default-authentication-plugin=mysql_native_password']
        container_name: database
        hostname: database
        image: mysql:8.0
        restart: always
        networks:
            - internal
        env_file: ./backend/.env

    backend:
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
        depends_on:
            - composer
            - database
        container_name: backend
        hostname: backend
        restart: always
        networks:
            - internal
            - external
        volumes:
            - ./backend:/usr/src/backend
        env_file: ./backend/.env

    webserver:
        depends_on:
            - backend
        container_name: webserver
        hostname: webserver
        image: nginx:stable-alpine
        env_file: ./backend/.env
        restart: always
        networks:
            - external
        ports:
            - 80:80
        volumes:
            - './backend:/usr/src/backend'
            - './docker/webserver/default.conf:/etc/nginx/conf.d/default.conf:ro'

    composer:
        container_name: composer
        hostname: composer
        image: composer:1.9.3
        restart: 'no'
        networks:
            - internal

networks:
    external:
        driver: bridge
    internal:
        driver: bridge
