# docker-compose.yml

version: '3.5'

services:
    database:
        command: ['--default-authentication-plugin=mysql_native_password']
        hostname: database
        image: mysql:8.0
        restart: always
        networks:
            - symfony_docker
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
            - "${MYSQL_PORT}:3306"

    application:
        build:
            context: .
            dockerfile: docker/application/Dockerfile
        depends_on:
            - composer
            - database
        hostname: application
        restart: always
        networks:
            - symfony_docker
        volumes:
            - ./app:/usr/src/app
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_PORT=${MYSQL_PORT}
            - APP_ENV=${APP_ENV}
            - JWT_PASSPHRASE=${JWT_PASSPHRASE}

    webserver:
        depends_on:
            - application
        hostname: webserver
        image: nginx:1.15.3-alpine
        restart: always
        networks:
            - symfony_docker
        volumes:
            - './app:/usr/src/app'
            - './docker/webserver/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - "${NGINX_PORT}:80"

    composer:
        hostname: composer
        image: composer/composer:alpine
        restart: 'no'
        networks:
            - symfony_docker

networks:
    symfony_docker:
        name: ${NETWORK_NAME}
        driver: bridge