# docker-compose.yml

version: '3.5'

services:
    database:
        command: ['--default-authentication-plugin=mysql_native_password']
        hostname: database
        image: mysql:8.0
        restart: always
        networks:
            - internal
        env_file: ./app/.env

    application:
        build:
            context: .
            dockerfile: docker/application/Dockerfile
        depends_on:
            - composer
            - database
        hostname: application
        restart: always
        networks:
            - internal
            - external
        volumes:
            - ./app:/usr/src/app
        env_file: ./app/.env

    webserver:
        depends_on:
            - application
        hostname: webserver
        image: nginx:stable-alpine
        env_file: ./app/.env
        restart: always
        networks:
            - external
        ports:
            - "80:80"
        volumes:
            - './app:/usr/src/app'
            - './docker/webserver/default.conf:/etc/nginx/conf.d/default.conf:ro'

    composer:
        hostname: composer
        image: composer:1.9.3
        restart: 'no'
        networks:
            - internal

networks:
    external:
        driver: bridge
    internal:
        driver: bridge
