# dev.yml

version: '3.5'

services:
    adminer:
        depends_on:
            - database
        hostname: adminer
        image: adminer
        ports:
            - "8081:8080"
        restart: always
        env_file: ./app/.env
        networks:
            - internal
            - external
