# dev.yml

version: '3.7'

services:

    application:
        environment:
            - XDEBUG_CONFIG=idekey=${XDEBUG_CODE} remote_host=${XDEBUG_HOST} remote_port=${XDEBUG_PORT} remote_enable=1

    adminer:
        depends_on:
            - database
        hostname: adminer
        image: adminer
        ports:
            - "${ADMINER_PORT}:8080"
        restart: always
