# dev.yml

version: '3.5'

services:
    database:
        env_file:
            - app/.env
        ports:
            - "${MYSQL_PORT}:3306"
        expose:
            - ${MYSQL_PORT}

    application:
        volumes:
            - ./docker/application/supervisor.conf:/etc/supervisor/supervisor.conf
        user: ${CURRENT_UID}
        env_file:
            - app/.env

    mailer:
        container_name: mailer
        restart: always
        image: schickling/mailcatcher
        depends_on:
            - application
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
            - symfony_docker

    messenger:
        container_name: messenger
        image: rabbitmq:3-management-alpine
        hostname: messenger
        restart: always
        depends_on:
            - application
        networks:
            - symfony_docker
        ports:
            - 5672:5672
            - 15672:15672
        user: ${CURRENT_UID}

    adminer:
        container_name: adminer
        depends_on:
            - database
        hostname: adminer
        image: adminer
        env_file:
            - app/.env
        restart: always
        networks:
            - symfony_docker
        ports:
            - "${ADMINER_PORT}:8080"

    webserver:
        ports:
            - "${NGINX_PORT}:80"

networks:
    symfony_docker:
        name: ${NETWORK_NAME}
        driver: bridge
            