# docker-compose.yml

version: '3.7'

services:
    database:
        command: ['--default-authentication-plugin=mysql_native_password']
        env_file:
            - ./docker/database/.env
        hostname: database
        image: mysql:8.0
        restart: always

    application:
        build:
            context: .
            dockerfile: docker/application/Dockerfile
        depends_on:
            - composer
            - database
        env_file:
            - ./docker/database/.env
        hostname: application
        restart: always
        volumes:
            - ./app:/usr/src/app

    webserver:
        depends_on:
            - application
        env_file:
            - ./docker/webserver/.env
        hostname: webserver
        image: nginx:1.15.3-alpine
        restart: always

    composer:
        hostname: composer
        image: composer/composer:alpine
        restart: 'no'
