# docker-compose.yml

version: '3.7'

services:

    application:
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}Test
            - XDEBUG_CONFIG=idekey=${DEBUG_CODE} remote_host=${DEBUG_HOST} remote_port=${DEBUG_PORT} remote_enable=1

    adminer:
        depends_on:
            - database
        hostname: adminer
        image: adminer
        ports:
            - "${ADMINER_PORT}:8080"
        restart: always
