# docker-compose.override.yml
version: '3.7'
services:
    application:
        volumes:
            - './app/:/usr/src/app'

    webserver:
        volumes:
            - './app/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

        ports:
            -   "${NGINX_PORT}:80"
            
    adminer:
        ports:
            - "${ADMINER_PORT}:8080"
