# docker-compose.override.yml
version: '3.7'

services:
    application:
        environment:
            XDEBUG_CONFIG: 'idekey=VSCODE remote_host=172.17.0.1 remote_port=9090 remote_enable=1'
        volumes:
            - './app/:/usr/src/app'

    webserver:
        env_file:
            - ./docker/webserver/.env
        volumes:
            - './app/public/:/usr/src/app'
            - './docker/webserver/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            -   '80:80'

    adminer:
        depends_on:
            - database
        hostname: adminer
        image: adminer
        ports:
            - "8080:8080"
        restart: always