# docker-compose.yml

version: '3.7'

services:
    database:
        env_file:
            - ./docker/database/.env

    application:
        env_file:
            - ./docker/application/.env
            - ./docker/application/.env.test
            - ./docker/database/.env

    webserver:
        env_file:
            - ./docker/webserver/.env
