# dev.yml

version: '3.3'

services:
    database:
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}Test
    application:
        environment:
            - APP_ENV=test
            - MYSQL_DATABASE=${MYSQL_DATABASE}Test
