# dev.yml

version: '3.7'

services:
    database:
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
    application:
        environment:
            - APP_ENV=dev
            - MYSQL_DATABASE=${MYSQL_DATABASE}
    adminer:
        depends_on:
            - database
        hostname: adminer
        image: adminer
        ports:
            - "${ADMINER_PORT}:8080"
        restart: always
