
# behat.yml
default:
    suites:
        default:
            paths:
                features: ../tests/functional
            contexts:
                - App\Tests\FeatureContext:
                    kernel: '@kernel'
                - Behat\MinkExtension\Context\MinkContext
                - Behatch\Context\RestContext
                - Behatch\Context\JsonContext

    extensions:
        Behat\Symfony2Extension:
            kernel:
                bootstrap: ./bootstrap.php
                class: App\Kernel

        Behat\MinkExtension:
            show_auto: true
            show_cmd: firefox %s
            base_url: "http://localhost"
            sessions:
                default:
                    symfony2: ~

        Behatch\Extension: ~
