#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# authentication_token:
#     path: /authentication_token
#     methods: ['POST']

api_login_check:
    path: /api/login_check
