api_platform:
    swagger:
        versions: [3]
        api_keys:
            JWT_TOKEN:
                name: Authorization
                type: header
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
